### ISSUE TITLE
consider releasing a new version (1.0.3 is not possible to be packaged for distributions)

### ISSUE THREAD

**Issue by anthraxx** [ioquatix/rubydns#61]
Hey, please consider releasing a new version. The current one (1.0.3) depends on celluloid = 0.16.0 which can't be met for a distribution level of packaging as it ships > 0.17. I have seen you made already adjustments so its able to switch to celluloid libraries from the 0.17 series.
I would highly appreciate if you could consider releasing a new version soon so I could package your library for our distribution (as rubydns its a hard dependency for a program I maintain).

cheers and thx

**Comment by ioquatix** [comment]
Sure okay :)

**Comment by ioquatix** [comment]
Hey, so I just reviewed where we are at with this.

We are still waiting on https://github.com/celluloid/celluloid/issues/698 to be resolved.

It's a problem which causes noisy output and in some cases incorrect behaviour.

Once this is sorted we can make the release here.

**Comment by anthraxx** [comment]
@ioquatix that sounds good, thank you very much for consideration. Also thanks that you already pinged them again :wink:

**Comment by icy** [comment]
Hi @ioquatix,

I used `rubydns-1.0.3` and I got a problem. When I send a `large` amount (say, 500) of non-existent queries to my resolver, the `actor` wil crash and the `rubydns` daemon stops responding. `non-existent` queries are like this

````
$RANDOM-$RANDOM-$RANDOM-$RANDOM.example.net
```

These queries would take `timeout` error, but it seems that `rubydns` and/or the `celluloid-0.16.0` (used by `rubydns-1.0.3`) couldn't handle them, and crash in the end. It's easy to generate this set of queries

````
#/bin/bash
_test() {
  count=100
  while (( count )); do
    dig +short $RANDOM-$RANDOM-$RANDOM-$RANDOM.example.net @localhost -p 5300 >/dev/null &
   (( count -- ))   
  done
}

_test & _test & _test & _test & _test & # 500 queries sent hopefully.
````

I have switched to `rubydns-<master>`, and it seems good. But the question is whethere this problem was acknowledged in the past?

I can provide more logs up request (My system sends all logs to a `elasticearch` instance so I haven't it now.)

Thanks a lot.

**Comment by ioquatix** [comment]
Thanks for this report. This is certainly important to be aware of. Ideally we will be releasing a new version of rubydns soon but there are still a few issues with celluloid to sort out.

**Comment by ioquatix** [comment]
Just touching base here. I'll try to put aside some time to review this soon.

**Comment by ioquatix** [comment]
@anthraxx there is a new release 2.0.0.pre.rc1 which no longer uses celluloid. Can you please try it out? Thanks so much for your time and patience.

@icy It would be awesome to stress test the new server. Can you try your stress test on the latest rc?

**Comment by ioquatix** [comment]
Has anyone had a chance to try out the rc yet?

**Comment by ioquatix** [comment]
2.0.0 has been released.
